// Generated by scripts/narration-durations.mjs. Do not edit by hand.
//
// Every number here is measured from a locked narration stem in
// curriculum/problem-solving/01-best-time-to-buy-and-sell-stock/audio/master. Re-run the script after a re-record.

export const narration = [
  { id: "scene-01", seconds: 94.549, audio: "scene-01.wav" },
  { id: "scene-02", seconds: 64.341, audio: "scene-02.wav" },
  { id: "scene-03", seconds: 62.805, audio: "scene-03.wav" },
  { id: "scene-04", seconds: 33.365, audio: "scene-04.wav" },
  { id: "scene-05", seconds: 75.947, audio: "scene-05.wav" },
  { id: "scene-06", seconds: 60.075, audio: "scene-06.wav" },
  { id: "scene-07", seconds: 38.997, audio: "scene-07.wav" },
  { id: "scene-08", seconds: 32.597, audio: "scene-08.wav" },
  { id: "scene-09", seconds: 35.669, audio: "scene-09.wav" },
] as const;

export type NarrationScene = (typeof narration)[number]["id"];

/** Total runtime with no gaps between scenes: 8:18. */
export const narrationSeconds = 498.345;
