// Generated by scripts/narration-durations.mjs. Do not edit by hand.
//
// Every number here is measured from a locked narration stem in
// curriculum/system-design/01-single-server/audio/master. Re-run the script after a re-record.

export const narration = [
  { id: "scene-01", seconds: 43.33, audio: "scene-01.wav" },
  { id: "scene-02", seconds: 63.9, audio: "scene-02.wav" },
  { id: "scene-03", seconds: 76.514, audio: "scene-03.wav" },
  { id: "scene-04", seconds: 91.477, audio: "scene-04.wav" },
  { id: "scene-05", seconds: 72.149, audio: "scene-05.wav" },
  { id: "scene-05b", seconds: 29.781, audio: "scene-05b.wav" },
  { id: "scene-06", seconds: 84.56, audio: "scene-06.wav" },
  { id: "scene-07", seconds: 54.749, audio: "scene-07.wav" },
] as const;

export type NarrationScene = (typeof narration)[number]["id"];

/** Total runtime with no gaps between scenes: 8:36. */
export const narrationSeconds = 516.46;
